enum Sym {
    TOKEN_AUTHOR("AUTHOR"),
    TOKEN_BOOL("BOOL"),
    TOKEN_BREAK("BREAK"),
    TOKEN_CASE("CASE"),
    TOKEN_CATCH("CATCH"),

    TOKEN_CHAR("CHAR"),
    TOKEN_CLASS("CLASS"),
    TOKEN_CONST("CONST"),
    TOKEN_CONTINUE("CONTINUE"),
    TOKEN_DEFAULT("DEFAULT"),

    TOKEN_DELETE("DELETE"),
    TOKEN_DO("DO"),
    TOKEN_DOUBLE("DOUBLE"),
    TOKEN_ELSE("ELSE"),
    TOKEN_ELSEIF("ELSEIF"),
    TOKEN_ENUM("ENUM"),

    TOKEN_FALSE("FALSE"),
    TOKEN_FLOAT("FLOAT"),
    TOKEN_FOR("FOR"),
    TOKEN_FRIEND("FRIEND"),
    TOKEN_GOTO("GOTO"),
    TOKEN_IDENTIFICATOR("IDENTIFICATOR"),
    TOKEN_IF("IF"),
    TOKEN_INLINE("INLINE"),
    TOKEN_INT("INT"),
    TOKEN_LONG("LONG"),

    TOKEN_NAMESPACE("NAMESPACE"),
    TOKEN_NEW("NEW"),
    TOKEN_OPERATOR("OPERATOR"),
    TOKEN_PRIVATE("PRIVATE"),

    TOKEN_PROTECTED("PROTECTED"),
    TOKEN_PUBLIC("PUBLIC"),
    TOKEN_REGISTER("REGISTER"),
    TOKEN_RETURN("RETURN"),
    TOKEN_SEPARATOR("SEPARATOR"),
    TOKEN_SHORT("SHORT"),

    TOKEN_SIGNED("SIGNED"),
    TOKEN_SIZEOF("SIZEOF"),
    TOKEN_STATIC("STATIC"),
    TOKEN_STRING("STRING"),
    TOKEN_STRUCT("STRUCT"),
    TOKEN_SWITCH("SWITCH"),
    TOKEN_TEMPLATE("TEMPLATE"),

    TOKEN_THIS("THIS"),
    TOKEN_THROW("THROW"),
    TOKEN_TRUE("TRUE"),
    TOKEN_TRY("TRY"),
    TOKEN_TYPEDEF("TYPEDEF"),
    TOKEN_TYPEID("TYPEID"),
    TOKEN_TYPENAME("TYPENAME"),
    TOKEN_UNION("UNION"),
    TOKEN_UNSIGNED("UNSIGNED"),

    TOKEN_USING("USING"),
    TOKEN_VIRTUAL("VIRTUAL"),
    TOKEN_VOID("VOID"),
    TOKEN_WHILE("WHILE"),

    OPERATOR_PLUS_PLUS("++"),
    OPERATOR_MINUS_MINUS("--"),
    OPERATOR_AND("&"),
    OPERATOR_STAR("*"),
    OPERATOR_PLUS("+"),
    OPERATOR_MINUS("-"),
    OPERATOR_TILD("~"),
    OPERATOR_EXCLAMATION("!"),
    OPERATOR_SLASH("/"),
    OPERATOR_MODULO("%"),
    OPERATOR_LOWER_LOWER("<<"),
    OPERATOR_GREATER_GREATER(">>"),
    OPERATOR_LOWER("<"),
    OPERATOR_GREATER(">"),
    OPERATOR_LOWER_EQUAL("<="),
    OPERATOR_GREATER_EQUAL(">="),
    OPERATOR_EQUAL_EQUAL("=="),
    OPERATOR_DIFFERENT("!="),
    OPERATOR_POWER("^"),
    OPERATOR_OR("|"),
    OPERATOR_AND_AND("&&"),
    OPERATOR_OR_OR("||"),
    OPERATOR_EQUAL("="),
    OPERATOR_STAR_EQUAL("*="),
    OPERATOR_SLASH_EQUAL("/*"),
    OPERATOR_MODULO_EQUAL("%="),
    OPERATOR_PLUS_EQUAL("+="),
    OPERATOR_MINUS_EQUAL("-="),
    OPERATOR_LOWER_LOWER_EQUAL("<<="),
    OPERATOR_GREATER_GREATER_EQUAL(">>="),
    OPERATOR_AND_EQUAL("&="),
    OPERATOR_POWER_EQUAL("^="),
    OPERATOR_OR_EQUAL("|=");

    public String str;
    Sym(String str) {
        this.str = str;
    }

    @Override
    public String toString() {
        return this.str;
    }
}
